# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Reddcoin
tagline:          Development blog
description:      Blog posts by Reddcoin developers
url:              http://blog.reddcoin.com

author:
  name:           Mathy Vanvoorden
  url:            https://github.com/MathyV

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/reddcoin-project/reddcoin-project.github.io
